### ISSUE TITLE
Información tutores: Usuario profesor alumno

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/instituto#127]
Crear método` isProfesorAlumno($alumno_id)`, en el modelo **App/User**, al que se le envía el id de un usuario (alumno) y devuelve _true_ en el caso de que el usuario imparta docencia a alguno de los grupos en el que está matriculado el alumno que se envía como parámetro o false en caso contrario.

**Comment by HectorDawDosMares** [comment]
@AntonioLV1999

**Comment by HectorDawDosMares** [comment]
#164
