### ISSUE TITLE
Información tutores: políticas de acceso

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/instituto#128]
La creación (POST) de los registros de la tabla **peticionesinformacion** puede ser realizada por el tutor del alumno (_isTutorAlumno()_) sobre el que se solicita información. Por otro lado, la modificación (PUT) así como el borrado (DELETE) únicamente pueden ser realizados por el tutor que creó el registro.

La creación (POST) de los registros de la tabla **respuestasprofesores** puede ser realizada por un profesor del grupo del que es tutor el que solicita información. Por otro lado, la modificación (PUT) así como el borrado (DELETE) únicamente pueden ser realizados por el profesor que creó el registro.

**Comment by HectorDawDosMares** [comment]
@RndDavid
