### ISSUE TITLE
Verificar centro

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/instituto#62]
Elimina, de los POST o PUT al endpoint centro, el atributo _verificado_, para que tenga que ser el superadministrador el que verifique todos los centros.
Crea una ruta _PUT /api/centro/verifica/{centro_id}_, que únicamente pueda ser ejecutada por el superadmin y que permita verificar la validez de un centro, poniendo a **true** el atributo _verificado_.

**Comment by ChristianAlbaladejo** [comment]
#100
